name: 'Markdown to Confluence'

inputs:
  repopath:
    description: 'Repo Path'
    required: true
    default: './'
  apikey:
    description: 'User'
    required: true
    default: '???'
  space:
    description: 'API Key'
    required: true
    default: '???'

runs:
    using: 'composite'
    steps:
    - run: go run ${{ github.action_path }}/main.go
      shell: bash
      env:
        INPUT_TEST_API_KEY: ${{ inputs.apikey }}
        INPUT_TEST_SPACE: ${{ inputs.space }}
        INPUT_REPO_PATH: ${{ inputs.repopath }} 
