name: Markdown to Confluence
inputs:
  key:
    description: 'the api key'
    required: true
    default: ''
  space:
    description: 'the confluence space'
    required: true
    default: ''
  username:
    description: 'the username'
    required: true
    default: ''
  repo:
    description: 'the repository foldername'
    required: true
    default: ''
  url:
    description: 'alternative atlassian url'
    required: false
    default: ''
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.key }} ${{ inputs.space }} ${{ inputs.username }} ${{ inputs.repo }} ${{ inputs.url }}
