name: Markdown to Confluence
description: "syncs github with confluence"
inputs:
  key:
    description: 'the api key'
    required: true
    default: ''
  space:
    description: 'the confluence space'
    required: true
    default: ''
  username:
    description: 'the username'
    required: true
    default: ''
  repo:
    description: 'the repository foldername'
    required: true
    default: ''
  url:
    description: 'alternative atlassian url'
    required: false
    default: ''
runs:
  using: docker
  image: Dockerfile
  env:
      CONFLUENCE_BASE_URL: ${{ inputs.url }}
      CONFLUENCE_SPACE: ${{ inputs.space }}
      CONFLUENCE_USERNAME: ${{ inputs.username }}
      CONFLUENCE_API_KEY: ${{ inputs.key }}
      PROJECT_PATH: ${{ inputs.repo }}