name: 'Markdown to Confluence'

inputs:
  repopath:
    description: 'Repo Path'
    required: true
    default: './'
  apikey:
    description: 'API key'
    required: true
    default: '???'
  user:
    description: 'User'
    required: true
    default: '???'
  space:
    description: 'Space'
    required: true
    default: '???'

runs:
    using: 'composite'
    steps:
    - run: go mod tidy ; go run ${{ github.action_path }}/main.go
      shell: bash
      env:
        INPUT_CONFLUENCE_API_KEY: ${{ inputs.apikey }}
        INPUT_CONFLUENCE_SPACE: ${{ inputs.space }}
        PROJECT_PATH: ${{ inputs.repopath }} 
        INPUT_CONFLUENCE_USERNAME: ${{ inputs.user }} 
