name: Markdown to Confluence
inputs:
  key:
    description: 'the api key'
    required: true
    default: ''
  space:
    description: 'the confluence space'
    required: true
    default: ''
  username:
    description: 'the username'
    required: true
    default: ''
  repo:
    description: 'the repository foldername'
    required: true
    default: ''
  parentID:
    description: 'the confluence parent page ID'
    required: true
    default: ''
  url:
    description: 'alternative atlassian url'
    required: false
    default: ''
  onlyDocs:
    description: 'copy all folders or only docs'
    required: true
    default: ''
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.key }} 
    - ${{ inputs.space }} 
    - ${{ inputs.username }} 
    - ${{ inputs.repo }} 
    - ${{ inputs.parentID }} 
    - ${{ inputs.url }}
    - ${{ inputs.onlyDocs }}
