title Code Methodology

@startuml

title Code Methodology


start
note right: node.Start(folderpath)
:Create node 
for root folder;

repeat

if (Valid files
exist in folder?) then (yes)
  :Set as alive;
  :For node create/update 
  a folder page;
  :Create/update attachments
  for each valid image;
  :Create/update pages
  for each markdown file
  & set folder page as 
  parent page;

else (no)
  :Set as dead;
endif
if (Folders exist?) then (yes)
  :Create node
  for each Folder;
if (node is alive?) then (yes)
  :Root for new node(s) 
  is previous node;
else (no)
   :Root for new node(s) 
  is previous previous node;
endif
else (no)
endif
repeat while (Were new 
nodes created?)
:Delete any pages
remotely where file
no longer exists;
note left: node.Delete()
stop

@enduml