@startuml
namespace markdown {
    class FileContents << (S,Aquamarine) >> {
        + MetaData <font color=blue>map</font>[string]<font color=blue>interface</font>{}
        + Body []byte

    }
}


@enduml
