@startuml
namespace markdown {
    class FileContents << (S,Aquamarine) >> {
        + MetaData <font color=blue>map</font>[string]<font color=blue>interface</font>{}
        + Body []byte

    }
    class author << (S,Aquamarine) >> {
        - name string
        - howmany int

    }
    class authors << (S,Aquamarine) >> {
        - append(item string) 
        - sort() 

    }
    class markdown.authors << (T, #FF7700) >>  {
    }
}


"markdown.[]author" #.. "markdown.authors"
@enduml
