@startuml
namespace node {
    interface APIClienter  {
        + CreatePage(root int, contents *markdown.FileContents, isroot bool) (int, error)
        + DeletePage(pageID int) error
        + UpdatePage(pageID int, pageVersion int64, pageContents *markdown.FileContents, originalPage confluence.PageResults) (bool, error)
        + FindPage(title string, many bool) (*confluence.PageResults, error)
        + UploadAttachment(filename string, id int, index bool, indexid int) error

    }
    class Node << (S,Aquamarine) >> {
        - treeLink *Tree
        - masterID int
        - id int
        - alive bool
        - path string
        - hasIndex bool
        - root *Node
        - branches []*Node
        - titles []string
        - images map[string]bool
        - mu *sync.RWMutex
        - indexPage bool
        - indexName string

        - checkIfRootAlive(fpath string) 
        - fileInDirectoryCheck(fpath string, checking bool, folders bool) bool
        - checkIfMarkDown(fpath string, checking bool) bool
        - checkIfMarkDownFile(checking bool, name string) bool
        - checkIfFolder(fpath string) bool
        - checkOtherFileTypes(fpath string, checking bool) bool 
        - checkIfGoFile(name string) 
        - checkForImages(name string, checking bool) bool 
        - checkNodeRootIsNil(name string) 
        - imageToBeUploaded(name string) bool
        - checkConfluencePages(newPageContents *markdown.FileContents) error
        - newPage(newPageContents *markdown.FileContents) error
        - createOrUpdatePage(newPageContents *markdown.FileContents, pageResult *confluence.PageResults) error
        - addContents(newPageContents *markdown.FileContents) 
        - checkPageID(pageResult confluence.PageResults) error
        - findPagesToDelete(id string) 
        - deletePages(children *confluence.PageResults) 
        - deletePage(id string) 
        - withinDirectory(base string, path string) bool
        - generateMaster() 
        - generateChildPages() 
        - generateFolderPage(hasIndex bool) error
        - generateTitles() (string, string)
        - generatePlantuml(fpath string) 
        - generatePlantumlImage(fpath string) error
        - generatePage(newPageContents *markdown.FileContents) error
        - iterate(justChecking bool, foldersOnly bool) bool
        - processGoFile(fpath string) error
        - processMarkDownIndex(path string) (*markdown.FileContents, error)
        - processMarkDown(path, fileName string) error
        - uploadFile(path string, isIndexPage bool) 

        + Start(projectMasterID int, projectPath string, onlyDocs bool) bool
        + Tree() 
        + Delete() 

    }
    class Tree << (S,Aquamarine) >> {
        - branches <font color=blue>map</font>[string]string

    }
    class iterator << (S,Aquamarine) >> {
        - mockiter int
        - isroot bool
        - pages []*page

        - append(root int, contents *markdown.FileContents, isroot bool) int

    }
    class mockclient << (S,Aquamarine) >> {
        - i *iterator

        + Print() 
        + CreatePage(root int, contents *markdown.FileContents, _ bool) (int, error)
        + DeletePage(pageID int) error
        + UpdatePage(pageID int, pageVersion int64, pageContents *markdown.FileContents, originalPage confluence.PageResults) (bool, error)
        + FindPage(title string, many bool) (*confluence.PageResults, error)
        + UploadAttachment(filename string, id int, index bool, indexid int) error

    }
    class page << (S,Aquamarine) >> {
        - title string
        - isroot bool
        - body string
        - root int
        - id int

    }
}

"node.APIClienter" <|-- "node.mockclient"

@enduml
