@startuml
namespace node {
    interface APIClienter  {
        + CreatePage(root int, contents *markdown.FileContents, isroot bool) (int, error)
        + DeletePage(pageID int) error
        + UpdatePage(pageID int, pageVersion int64, pageContents *markdown.FileContents, originalPage confluence.PageResults) (bool, error)
        + FindPage(title string, many bool) (*confluence.PageResults, error)
        + UploadAttachment(filename string, id int) error

    }
    class Node << (S,Aquamarine) >> {
        - id int
        - alive bool
        - path string
        - root *Node
        - branches []*Node
        - titles []string
        - mu sync.RWMutex

        - checkIfRootAlive(fpath string) 
        - fileInDirectoryCheck(fpath string, checking bool, folders bool) bool
        - checkIfMarkDown(fpath string, checking bool) bool
        - checkIfMarkDownFile(checking bool, name string) bool
        - checkIfFolder(fpath string) bool
        - checkOtherFileTypes(fpath string) 
        - checkIfGoFile(name string) 
        - checkForImages(name string) 
        - checkNodeRootIsNil(name string) 
        - checkConfluencePages(newPageContents *markdown.FileContents) error
        - addContents(newPageContents *markdown.FileContents) 
        - checkPageID(pageResult confluence.PageResults) error
        - findPagesToDelete(id string) 
        - deletePages(children *confluence.PageResults) 
        - deletePage(id string) 
        - generateMaster() 
        - generateChildPages() 
        - generateFolderPage() error
        - generateTODOPage(percentage string) 
        - generateTitles() (string, string)
        - generatePlantuml(fpath string) 
        - generatePlantumlImage(fpath string) 
        - generatePage(newPageContents *markdown.FileContents) error
        - iterate(justChecking bool, foldersOnly bool) bool
        - processGoFile(fpath string) error
        - processMarkDown(path string) error
        - uploadFile(path string) 

        + Start(projectPath string) bool
        + Delete() 

    }
}


@enduml
